# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/node-pkgs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      textlint:
        patterns:
          - "textlint"
          - "textlint-*"
    cooldown:
      default-days: 7
      semver-major-days: 7
      semver-minor-days: 7
      semver-patch-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Asia/Tokyo"
