[formatter.md]
command = "markdownlint-cli2"
options = ["--config", ".config/.markdownlint-cli2.jsonc"]
includes = ["*.md"]
priority = 1

[formatter.text]
command = "textlint"
options = ["--config", ".config/textlintrc.json"]
includes = ["*.md"]
priority = 2

[formatter.url]
command = "lychee"
options = ["--config", ".config/lychee.toml"]
includes = ["*.md"]
priority = 3

[formatter.spell]
command = "cspell"
includes = ["*.md"]
priority = 4
