name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# Restrict default GITHUB_TOKEN permissions.
permissions:
  contents: read

jobs:
  check-nix:
    name: Check Nix

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
        with:
          use-flakehub: false

      # devShells.default が正常にビルド（インスタンス化）できるかチェック
      - name: Check devShell (default)
        run: nix develop .#default --command true

      # node更新用のshellも一応チェック
      - name: Check devShell (node)
        run: nix develop .#node --command true
